
#Phase A length (NS)
X1 = 5
#Phase B length (EW)
X2 = 6

#time for car to cross
S = 3

#Car arrival interval [1=North, 2=East, 3=South, 4=West]
# if value is less than 0, it will be ignored.
A1 = 2
A2 =-1
A3 = 3
A4 = -1
