
#Phase A length (NS)
X1 = 7

#Phase B length (EW)
X2 = 7

#time for car to cross
S = 5

#Car arrival interval [1=North, 2=East, 3=South, 4=West]
# if value is less than 0, it will be ignored.
A1 = -1
A2 = -1
A3 = -1
A4 = -1
